# Generated by Django 5.1.4 on 2026-04-24 21:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('journal_code', models.CharField(default='ACH', max_length=10)),
                ('entry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('posted', 'Comptabilisé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='documents.invoice')),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='tenants.organization')),
            ],
            options={
                'db_table': 'ledger_journalentry',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(db_index=True, max_length=10)),
                ('account_label', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.PROTECT, related_name='account_entries', to='tenants.organization')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
            options={
                'db_table': 'ledger_accountentry',
                'ordering': ['account_code'],
            },
        ),
    ]
