# Generated by Django 5.1.4 on 2026-04-25 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_add_journalentryaudit'),
        ('tenants', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lettering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_code', models.CharField(db_index=True, max_length=10)),
                ('account_code', models.CharField(db_index=True, max_length=10)),
                ('is_balanced', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letterings', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.PROTECT, related_name='letterings', to='tenants.organization')),
            ],
            options={
                'db_table': 'ledger_lettering',
                'ordering': ['account_code', 'letter_code'],
            },
        ),
        migrations.CreateModel(
            name='LetteringLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lettering_line', to='ledger.accountentry')),
                ('lettering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.lettering')),
            ],
            options={
                'db_table': 'ledger_letteringline',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='lettering',
            constraint=models.UniqueConstraint(fields=('org', 'account_code', 'letter_code'), name='unique_lettering_code_per_org_account'),
        ),
    ]
