# Generated by Django 5.1.4 on 2026-04-25 18:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_add_lettering'),
        ('tenants', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(db_index=True, max_length=10)),
                ('account_label', models.CharField(blank=True, max_length=255)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('reconciled', 'Rapproché')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_bank_statements', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='tenants.organization')),
            ],
            options={
                'db_table': 'ledger_bankstatement',
                'ordering': ['-period_to', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('match_status', models.CharField(choices=[('unmatched', 'Non rapproché'), ('matched', 'Rapproché (auto)'), ('manual', 'Rapproché (manuel)'), ('ignored', 'Ignoré')], db_index=True, default='unmatched', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reconciliation_lines', to='ledger.accountentry')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.bankstatement')),
            ],
            options={
                'db_table': 'ledger_bankstatementline',
                'ordering': ['transaction_date', 'id'],
            },
        ),
    ]
