# Generated by Django 5.1.4 on 2026-04-26 15:13

import fernet_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_add_chart_of_accounts'),
        ('tenants', '0003_add_org_creation_request'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chartofaccounts',
            name='unique_chart_org_code',
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='label',
            field=fernet_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccounts',
            unique_together={('org', 'account_code')},
        ),
    ]
