# Generated by Django 5.1.4 on 2026-04-24 21:50

import django.db.models.deletion
import fernet_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('extracted', 'Extrait'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('error', 'Erreur')], db_index=True, default='pending', max_length=20)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('vendor_name', fernet_fields.EncryptedCharField(blank=True, max_length=255)),
                ('vendor_siren', fernet_fields.EncryptedCharField(blank=True, max_length=9)),
                ('vendor_siren_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ht_amount', fernet_fields.EncryptedCharField(blank=True, max_length=30)),
                ('tva_amount', fernet_fields.EncryptedCharField(blank=True, max_length=30)),
                ('ttc_amount', fernet_fields.EncryptedCharField(blank=True, max_length=30)),
                ('raw_text', fernet_fields.EncryptedTextField(blank=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.organization')),
            ],
            options={
                'db_table': 'documents_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('queue', models.CharField(choices=[('pdf', 'Queue PDF'), ('llm', 'Queue LLM'), ('default', 'Queue par défaut')], default='default', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('started', 'Démarré'), ('success', 'Succès'), ('failure', 'Échec'), ('retry', 'Relancé')], db_index=True, default='queued', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.invoice')),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='tenants.organization')),
            ],
            options={
                'db_table': 'documents_processingjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
